/**
 * Core domain types shared by the server, web app, and mobile app.
 *
 * Every entity carries a `workspaceId`. A workspace is the tenant boundary:
 * a single personal user gets exactly one workspace today, but the schema
 * already supports a workspace having multiple members later without a
 * migration of these shapes.
 */

export const LIFE_DOMAINS = ["study", "business", "social", "relax"] as const;
export type LifeDomain = (typeof LIFE_DOMAINS)[number];

export type ISODate = string; // "YYYY-MM-DD"
export type ISODateTime = string; // full ISO 8601 timestamp

export type GoalStatus = "active" | "paused" | "completed" | "abandoned";

export interface Goal {
  id: string;
  workspaceId: string;
  domain: LifeDomain;
  title: string;
  description?: string;
  targetDate?: ISODate;
  weeklyTargetMinutes?: number;
  obstacle?: string;
  ifThenPlan?: string;
  keyResultTarget?: number;
  keyResultUnit?: string;
  keyResultCurrent?: number;
  status: GoalStatus;
  createdAt: ISODateTime;
  updatedAt: ISODateTime;
}

export type RecurrenceFrequency = "once" | "daily" | "weekly" | "monthly";

export interface RecurrenceRule {
  freq: RecurrenceFrequency;
  /** For weekly: 0=Sunday..6=Saturday. Omitted means "any day" for daily. */
  daysOfWeek?: number[];
  /** How many occurrences per matching day, e.g. "reach out to 10 people/day" -> handled via count on the step, not here. */
  interval?: number; // every N days/weeks/months, default 1
  /** Recurrence stops being scheduled after this date (inclusive). Defaults to the goal's targetDate. */
  until?: ISODate;
}

export type StepStatus = "pending" | "active" | "done" | "archived";

export interface Step {
  id: string;
  workspaceId: string;
  goalId: string;
  domain: LifeDomain;
  title: string;
  notes?: string;
  estimatedMinutes: number;
  /** 1 = highest priority, 5 = lowest. Used by the scheduler as a tiebreaker. */
  priority: number;
  recurrence: RecurrenceRule;
  status: StepStatus;
  /** Earliest date this step may be scheduled. */
  earliestDate?: ISODate;
  /** True if generated by the AI breakdown suggestion (vs. user authored). */
  aiSuggested: boolean;
  createdAt: ISODateTime;
  updatedAt: ISODateTime;
}

export type TaskInstanceStatus =
  | "scheduled"
  | "completed"
  | "missed"
  | "skipped";

/**
 * A single concrete occurrence of a Step placed on the calendar.
 * Recurring steps expand into many TaskInstances.
 */
export interface TaskInstance {
  id: string;
  workspaceId: string;
  stepId: string;
  goalId: string;
  domain: LifeDomain;
  title: string;
  scheduledDate: ISODate;
  startMinute?: number; // minutes from midnight, if time-of-day is placed
  durationMinutes: number;
  status: TaskInstanceStatus;
  completedAt?: ISODateTime;
  /** True when this instance was auto-rescheduled from an earlier missed date. */
  rescheduledFrom?: ISODate;
  createdAt: ISODateTime;
  updatedAt: ISODateTime;
}

/** Per-domain minutes of capacity a user has on a given weekday, before energy adjustment. */
export type DayCapacityTemplate = Record<LifeDomain, number>;

export interface WeeklyCapacityTemplate {
  /** Index 0=Sunday..6=Saturday */
  days: DayCapacityTemplate[];
}

export const DEFAULT_WEEKLY_CAPACITY: WeeklyCapacityTemplate = {
  days: [
    { study: 60, business: 60, social: 60, relax: 60 }, // Sunday
    { study: 90, business: 120, social: 30, relax: 30 }, // Monday
    { study: 90, business: 120, social: 30, relax: 30 }, // Tuesday
    { study: 90, business: 120, social: 30, relax: 30 }, // Wednesday
    { study: 90, business: 120, social: 30, relax: 30 }, // Thursday
    { study: 60, business: 90, social: 60, relax: 45 }, // Friday
    { study: 60, business: 60, social: 90, relax: 60 }, // Saturday
  ],
};

export interface TaskCompletionRecord {
  date: ISODate;
  scheduledCount: number;
  completedCount: number;
  missedCount: number;
  scheduledMinutes: number;
  completedMinutes: number;
}

export type EnergyTrend = "rising" | "falling" | "stable";

export interface EnergyState {
  date: ISODate;
  /** 0 (depleted) .. 100 (fully fresh) */
  score: number;
  trend: EnergyTrend;
  /** Multiplier applied to the day's base capacity, e.g. 0.6 .. 1.15 */
  loadMultiplier: number;
  signals: {
    completionRate7d: number;
    completionRate14d: number;
    missedStreak: number;
    completedStreak: number;
    overdueLoad: number;
  };
}

export interface DomainBalanceEntry {
  domain: LifeDomain;
  scheduledMinutes: number;
  completedMinutes: number;
  completionRate: number;
  shareOfTotal: number;
  neglected: boolean;
}

export interface PriorityReport {
  windowStart: ISODate;
  windowEnd: ISODate;
  domains: DomainBalanceEntry[];
  neglectedDomains: LifeDomain[];
}

export interface StudyMaterialItem {
  id: string;
  title: string;
  estimatedMinutes: number;
  /** 1 (easy) .. 5 (hard). Harder topics get scheduled earlier and reviewed more. */
  difficulty: number;
}

export interface StudyPlanDay {
  date: ISODate;
  items: { materialId: string; title: string; minutes: number; isReview: boolean }[];
  totalMinutes: number;
}

export interface StudyPlan {
  goalId: string;
  examDate: ISODate;
  days: StudyPlanDay[];
}
